apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 192.168.44.44:8082/docker_registry/frontend:1.0
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          value: http://backend-service:5001
      imagePullSecrets:
      - name: regcred
